# Generated by Django 5.1.5 on 2025-02-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_exerpt_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exerpt',
            new_name='excerpt',
        ),
    ]
