# Generated by Django 5.1.5 on 2025-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uploadedimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(default='no description...', null=True),
        ),
    ]
