# Generated by Django 5.1.5 on 2025-02-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_websitebannerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitebannerimage',
            old_name='image',
            new_name='banner',
        ),
    ]
